### PR TITLE
Allow odmOptions to mongodb subscriber

### PR DESCRIPTION
**Pull request by markitosgv**
For example if you want to take care about collation you need to add a 4th parameter on ->paginate() method like this:

```
return $paginator->paginate($builder, 1, 10, [Paginator::ODM_QUERY_OPTIONS => ['collation' => ['locale' => 'en', 'strength' => 2]]]);
```

### CODE REVIEW

**Review by garak — CHANGES_REQUESTED** [review]
Documentation needs to be updated as well

**Comment by markitosgv** [comment]
@garak added configuration doc

**Review by garak — APPROVED** [review]

**Comment by markitosgv** [comment]
@garak do you plan to do a release?? thanks!

**Comment by garak** [comment]
> @garak do you plan to do a release?? thanks!

Yes, probably in next week or so

**Pull request merged**
