### PR TITLE
Add support for Doctrine ODM PHPCR

### PR DESCRIPTION
**Pull request by hason**

### CODE REVIEW

**Comment by hason** [comment]
ping @pilot @PedroTroller

**Comment by l3pp4rd** [comment]
sadly do not have permissions to manage this one :) @mbontemps @weaverryan maybe you could merge or add me back to contributors.

**Comment by weaverryan** [comment]
I'm not sure who is in charge of the repo, tbh - @PedroTroller @pilot - you were the last committers. Who should be maintaining this repo?

**Comment by ahilles107** [comment]
Hey, can we merge that feature? Who can do this?

**Comment by l3pp4rd** [comment]
have no access anymore :) PR seems to be OK

**Comment by ahilles107** [comment]
There is many OK Pr's waiting to be merged. @l3pp4rd Do you know who can have access to it?

**Comment by l3pp4rd** [comment]
sadly I do not have permissions for this repository, only for bundle. @mbontemps could you update permissions? @knplabs anyone?

**Comment by docteurklein** [comment]
@l3pp4rd oops! we must have forgotten to add you on this repo.
Anyway you should now have write access!
Cheers o/

**Comment by l3pp4rd** [comment]
thanks @docteurklein ;)

**Comment by ahilles107** [comment]
@l3pp4rd how about library new release with new features? And looks like KnpLabs/KnpPaginatorBundle still require version ~1.2 so even with new release of library it will be not used by KnpLabs/KnpPaginatorBundle - i'm right?

**Pull request merged**
