### PR TITLE
Fix branch-alias to match 1.3

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
ping @l3pp4rd.

Travis fail is not related to my PR.

**Comment by l3pp4rd** [comment]
hi, I do not have access to this repository anymore, but yes of course it is not related :)

**Comment by Soullivaneuh** [comment]
Hmm who is the maintainer so? :-)

**Comment by Soullivaneuh** [comment]
Found some.

ping @pilot @leonex-cstoller! :-)

**Comment by Soullivaneuh** [comment]
Thanks! :+1:

**Pull request merged**
