### PR TITLE
adding manual hinting for UsesPaginator subscriber

### PR DESCRIPTION
**Pull request by gondo**
https://github.com/KnpLabs/KnpPaginatorBundle/issues/276#issuecomment-59019534

### CODE REVIEW

**Comment by ANtlord** [comment]
Hello! When will PR be closed?

**Comment by svscorp** [comment]
Merged commit didn't fix the issue #276 btw.

````
Cannot count query which selects two FROM components, cannot make distinction
````

**Comment by jspizziri** [comment]
@svscorp , The reason that this didn't "fix" the issue in the KNP Paginator is because of a dependency mismatch.  If you [look here](https://github.com/KnpLabs/KnpPaginatorBundle/blob/master/composer.json), you will see that Paginator is using version ~1.2, and this fix is in the [1.3 release](https://github.com/KnpLabs/knp-components/compare/1.3.0...master)

For this to actually fix the paginator that version needs to be upgraded from ~1.2 to ~1.3, which is going to require some testing.

**Comment by jspizziri** [comment]
+1, this didn't fix the issue, v1.2.5 is still the only version which works.

**Pull request merged**
