### PR TITLE
Fixes missing Use statement

### PR DESCRIPTION
**Pull request by bjoernHeneka**
PaginatorInterface was not included in this file...

### CODE REVIEW

**Comment by gkawka** [comment]
@polc can you merge this PR? 🙏

**Comment by polc** [comment]
Looks good thanks @bjoernHeneka

**Comment by gkawka** [comment]
@polc thx for merge. Any chance on soon release? :)

**Comment by polc** [comment]
Here we go : https://github.com/KnpLabs/knp-components/releases/tag/v1.3.9 :)

**Comment by gkawka** [comment]
You are my hero mister ;)

**Pull request merged**
