### PR TITLE
Add getTotalItemCount in PaginationInterface

### PR DESCRIPTION
**Pull request by OsoianMarcel**
The method **getTotalItemCount** must be part of PaginationInterface

```
{# total items count #}
<div class="count">
    {{ pagination.getTotalItemCount }}
</div>
```

### CODE REVIEW

**Comment by NiR-** [comment]
I'm not sure that's really needed. As stated by the dockblock on the class, methods defined in it are the one needed for the paginator to populate pagination data. Which data are available from the pagination is up to the implementor and can vary from an implementation to another.

**Comment by OsoianMarcel** [comment]
@NiR- IDE Warning: Method not found
4xsp62n

**Comment by NiR-** [comment]
Have you tried `getTotalItemCount()` or `totalItemCount`? If it doesn't work either, I think the problem comes from twig plugin which doesn't resolve the concrete implementation but the interface.

**Comment by OsoianMarcel** [comment]
@NiR- The problem is not from Twig Plugin.

Look at phpDoc: https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/Paginator.php#L81

Look here: uq2ha8q

**Comment by NiR-** [comment]
Oh indeed! Well I don't know the whole history of the project, thus I'm not sure if that was done on purpose, if it's a mistake.

**Comment by hkdobrev** [comment]
This was also discussed here https://github.com/KnpLabs/KnpPaginatorBundle/issues/401

I also think the interface should include that, because:

- The use of the total count is often needed in nominal cases.
- I think each implementation must provide it as it's a getter that most if not all implementations would have (in the rare case that it can't it could throw an exception)
- The application code should not need to use inline comments like it was suggested in the other discussion to make static analysers happy. Reliance on the interface should be enough for most cases.
- Every implementation extending the abstract one would already have the method.

/cc @nicolasmure @thim81

**Comment by garak** [comment]
Method was added in 44d0b0bc73f77c0003c86ffde2591c06f769d68 and is now present in branch 2

**Pull request closed without merging**
