### PR TITLE
Fix dispatcher compatibility check for SF < 4.3

### PR DESCRIPTION
**Pull request by alexchoisy**
This change fixes an issue introduced in version 2.4.1 with PR #267 

Related issue : #270

### CODE REVIEW

**Comment by michaljusiega** [comment]
After merge this patch: 
`User Deprecated: Since symfony/event-dispatcher 5.1: Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy is deprecated, use the event dispatcher without the proxy.`

**Comment by garak** [comment]
> After merge this patch:
> `User Deprecated: Since symfony/event-dispatcher 5.1: Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy is deprecated, use the event dispatcher without the proxy.`

That was the rationale of previous behavior: we can't rely on existance of LegacyEventDispatcherProxy. because it still exists in Symfony 5.1 (but it's deprecated).
What is still unclear to me is the reason why Symfony complains about such class, even if we don't use it.

Anyway, I guess that it's better to keep deprecation message in 5.1 and keep library working in 3.4
In next major version we'll drop support for Symfony 3.4 (see #222)

**Comment by alexchoisy** [comment]
Doesn't the deprecation notice come from the constructor line ? 
https://github.com/KnpLabs/knp-components/blob/8486446af9591c9c3decaae6c234739288c80a5f/src/Knp/Component/Pager/Paginator.php#L62

Do we need to decorate the eventDispatcher even when Paginator's internal dispatch function acts as the compatibility checker ?

**Comment by garak** [comment]
In a Symfony 5 project, you should not have `Symfony\Component\EventDispatcher\Event` class

**Pull request merged**
