### PR TITLE
Ordenación correcta por campo de tipo datetime, incluidos valores nulos

### PR DESCRIPTION
**Pull request by eduardo79**
Que os parece

### CODE REVIEW

**Comment by ostrolucky** [comment]
This doesn't make sense. You can compare DateTime objects directly, no need to cast them to strings. Current code works fine with DateTime objects.

**Comment by eduardo79** [comment]
If one field in ddbb have a null value this dont work

**Comment by ostrolucky** [comment]
It does https://3v4l.org/DlhTq
No need to cast null to `0000-00-00 00:00:00`

**Comment by polc** [comment]
Hello @eduardo79, thanks for contributing! Date comparison look fine for now, If you still have problem, do not hesitate to create an issue.

**Pull request closed without merging**
